bottle comment tag system implementation
CIA-Homebrew/BJCP-Scoresheet pull request #118
Opened 2020-11-26 19:14 UTC by PH-Lazurous

2020-11-27 00:25 UTC, PH-Lazurous commented
#101

2020-11-27 03:54 UTC, prphntm63 requested changes

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +  let bottleComment = $("input#bottle_inspection_comment");
This is never used. Either remove the redeclarations in lines 581 or remove here.

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +  let quickCommentsOptions = $(".quick-comments-options");
These should be type `const` if never redeclared

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +  //- Initialize and setup our bottle comments
Since you aren't declaring any functions here, I would recommend wrapping this whole section in a function called something like `initializeQuickBottleComments` or something and then calling that in the `$(document).ready()` block. Plus, it helps separate the bottle comment setup logic from the rest of the script.

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +    let _com_sec = $("<div></div>");
Nitpick - this would be more semantically readable if written as `_comment_section` IMO

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +  let quickCommentsOptions = $(".quick-comments-options");
Actually, looking at it most of your declarations should probably be `const`. I've been taught that you should default to `const` as it is more conservative and prevents accidental redeclarations during code refactoring.

https://stackoverflow.com/questions/41086633/why-most-of-the-time-should-i-use-const-instead-of-let-in-javascript

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +      let f = $(".quick-comments-options").find(`span[data-value=${dv}]`);
Getting a browser error here:
```
Uncaught (in promise) Error: Syntax error, unrecognized expression: span[data-value=]
    at Function.se.error (jquery-3.4.1.min.js:2)
    at se.tokenize (jquery-3.4.1.min.js:2)
    at se.select (jquery-3.4.1.min.js:2)
    at Function.se [as find] (jquery-3.4.1.min.js:2)
    at k.fn.init.find (jquery-3.4.1.min.js:2)
    at insertBottleTag (scoresheet.js:617)
    at scoresheet.js:643
    at Array.forEach (<anonymous>)
    at buildQuickCommentInput (scoresheet.js:641)
    at scoresheet.js:685
```

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +  $("div.quick-comments-toggler").click(function () {
I don't see a DOM element `.quick-comments-toggler`

2020-11-27 03:54 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +      tag = comment.clone();
ES6 spread operator is more efficient, I believe 

`tag=[...comment]`

2020-11-27 03:54 UTC, prphntm63 commented on views/scoresheet.pug
> +                    .small.form-text.text-muted Use the <span style="font-family: Courier, monospace;">ENTER</span> or <span style="font-family: Courier, monospace;">COMMA</span> key to add custom co
Nitpick - should probably word this a bit better. The first time I tried it I clicked into the box and pressed "comma" to try to create a new custom field lol

2020-11-27 03:55 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +  let bottleComment = $("input#bottle_inspection_comment");
Yep .. that was moved to a different method and forgot to remove.

2020-11-27 03:56 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +  let quickCommentsOptions = $(".quick-comments-options");
Yea these actually should go away in a later version and just convert it to a self contained module/plugin.

2020-11-27 03:58 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +  //- Initialize and setup our bottle comments
Again my thought (post PR) was to just wrap this in a module and clean up the code completely out of this JS file.

2020-11-27 03:59 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +  //- Initialize and setup our bottle comments
I agree, but we can wrap it in a setup function to compartmentalize it for now. Will make it easier to "pull out" when the time comes IMO

2020-11-27 03:59 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +    let _com_sec = $("<div></div>");
I can, most of my localized variables I always prepend with a _ just to notate local usage only. But fair point.

2020-11-27 04:00 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +  $("div.quick-comments-toggler").click(function () {
Remnants, I'll purge. I had a button that could hide the quick comments by default and only show when the user wanted them but it seems useless post implementation.

2020-11-27 04:03 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +      tag = comment.clone();
Hmmm possibly but it would also merge the original element with events when I want a new element that gets appended with a new set of events to be determined later.

2020-11-27 04:04 UTC, PH-Lazurous commented on views/scoresheet.pug
> +                    .small.form-text.text-muted Use the <span style="font-family: Courier, monospace;">ENTER</span> or <span style="font-family: Courier, monospace;">COMMA</span> key to add custom co
I'm also open to input on wording, I'm the worst when it comes to frontend 'hints'.

2020-11-27 04:05 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +      tag = comment.clone();
Nope, spreading an object clones it _one level deep_. Since you have one level here, the deep clone is unnecessary I think.

2020-11-27 04:06 UTC, prphntm63 commented on views/scoresheet.pug
> +                    .small.form-text.text-muted Use the <span style="font-family: Courier, monospace;">ENTER</span> or <span style="font-family: Courier, monospace;">COMMA</span> key to add custom co
Honestly I couldn't think of better wording either lol. I guess if enough users complain we'll get feedback for what it _should_ say

2020-11-27 04:08 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +  //- Initialize and setup our bottle comments
I might be able to do this easily enough now that I think about it, get back to you on this.

2020-11-27 04:17 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +      tag = comment.clone();
I guess now that I look at that particular instance I'm mainly cloning for the data not appending events so spread is fine, I could see that being an issue (specifically around JQuery events) effecting multiple elements without using their clone methods because of the element hierarchy, at least in older JQuery versions.

2020-11-27 04:18 UTC, prphntm63 commented on public/javascripts/scoresheet.js
> +      tag = comment.clone();
Right, if you are cloning a jquery element, use `.clone()`. But here it looks like you are cloning either an array or string

2020-11-27 05:07 UTC, PH-Lazurous commented on public/javascripts/scoresheet.js
> +      tag = comment.clone();
By the way the way the method works if it's an element object if it's a found object of an existing tag in the 'list', so it would be a JQuery object at that point. 

```javascript
        let f = $(".quick-comments-options").find(`span[data-value=${dv}]`);
        if (f.length === 1) {
          insertBottleTag(f);
          //- Hide the one that is already there
          f.toggle(false);
          return;
        }
```

Other than that I'm expecting a string to form an object from scratch. based on a JQuery created element 

```javascript
tag = formTagObject(_c);
```

and 

```javascript
 let formTagObject = (comment) => {
    let _com_tpl = $("<span></span>");
    _com_tpl
      .data("data-value", comment["data-text"].replace(/\s+/g, ""))
      .attr("data-value", comment["data-text"].replace(/\s+/g, ""))
      .text(comment["data-text"])
      .addClass(comment.style)
      .addClass(" mx-1 px-1 py-1")
      .css("cursor", "pointer");

    return _com_tpl;
  };
```

2021-01-26 20:47 UTC, PH-Lazurous commented
Going to close this as this branch is no longer applicable to the solution for this issue/suggestion.

2021-01-26 20:47 UTC, closed without merging